### ISSUE TITLE
need some help in using deepks

### ISSUE THREAD

**Issue by Weizhang88** [deepmodeling/abacus-develop#5405]
### Details

**image**: deepks-abacus:3.7.5v1 with c2_m4_cpu from [https://bohrium.dp.tech/notebooks/63271724759]
My systems consist of various elements with differing atoms for HF-H₂O. Some systems exclusively contain water, while others include different HF molecules or varying water molecules. The [jle.orb ] was produced using HF-H₂O systems [HF-wat.tar.gz](https://github.com/user-attachments/files/17626377/HF-wat.tar.gz)
and was applied across all the systems.

The data files and input files are attached.

**error shows** : 

2024-11-05 10:43:23,018 - INFO : job: d800c44a04adeeffbc4cda66bd4ecd451cb7f8c2 submit; job_id is 15244823:job_group_id:13620781
2024-11-05 10:43:23,292 - INFO : job: ea14bec953e846ba7cf888fdfe25d7735d428929 submit; job_id is 15244825:job_group_id:13620781
2024-11-05 10:43:23,534 - INFO : job: 44858ce791c6f4287153e47c54555a4290ccf508 submit; job_id is 15244826:job_group_id:13620781
2024-11-05 10:44:19,216 - ERROR : request error status_code:404 reason: Not Found body: 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>67298683176F703739B4735E</RequestId>
  <HostId>bohrium.oss-cn-zhangjiakou.aliyuncs.com</HostId>
  <Key>278/422/job/278/12621841/out.zip</Key>
  <EC>0026-00000001</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0026-00000001</RecommendDoc>
</Error>

2024-11-05 10:44:19,239 - ERROR : request error status_code:404 reason: Not Found body: 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>67298683460E903335ABDB2C</RequestId>
  <HostId>bohrium.oss-cn-zhangjiakou.aliyuncs.com</HostId>
  <Key>278/422/job/278/12621841/out.zip</Key>
  <EC>0026-00000001</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0026-00000001</RecommendDoc>
</Error>

2024-11-05 10:44:20,265 - ERROR : request error status_code:404 reason: Not Found body: 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>67298684DE6F4232377D3101</RequestId>
  <HostId>bohrium.oss-cn-zhangjiakou.aliyuncs.com</HostId>
  <Key>278/422/job/278/12621841/out.zip</Key>
  <EC>0026-00000001</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0026-00000001</RecommendDoc>
</Error>

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by JohnYan98** [comment]
It appears to be an environment-related issue. You might consider running this project on the Bohrium platform (https://bohrium.dp.tech/), as it has been tested and confirmed to work using your systems there.

**Comment by Weizhang88** [comment]
> It appears to be an environment-related issue. You might consider running this project on the Bohrium platform (https://bohrium.dp.tech/), as it has been tested and confirmed to work using your systems there.

This project was ran on the Bohrium platform and encountered the errors mentioned above. The error log files was contained in the attached file.

**Comment by JohnYan98** [comment]
> > It appears to be an environment-related issue. You might consider running this project on the Bohrium platform (https://bohrium.dp.tech/), as it has been tested and confirmed to work using your systems there.
> 
> This project was ran on the Bohrium platform and encountered the errors mentioned above. The error log files was contained in the attached file.

To confirm, which command are you using to run the script: bash run.sh or bash run_dpdispatcher.sh? I used bash run_dpdispatcher.sh, filled in the email, password, and program_id fields with my account information, and it worked as expected.

Here's the complete machines_dpdispatcher.yaml file setup I used:

```yaml
scf_machine:
  resources:
    task_per_node: 8
  dispatcher: dpdispatcher
  dpdispatcher_resources:
    number_node: 1
    cpu_per_node: 16
    group_size: 5
    source_list: [/opt/intel/oneapi/setvars.sh]
  sub_size: 1
  dpdispatcher_machine:
    context_type: lebesguecontext
    batch_type: lebesgue
    local_root: ./
    remote_profile:
      email: *****
      password: *****
      program_id: *****
      input_data:
        log_file: log.scf
        err_file: err.scf
        job_type: indicate
        grouped: true
        job_name: deepks-scf
        disk_size: 100
        scass_type: c32_m128_cpu # machine type
        platform: ali
        image_name: registry.dp.tech/dptech/prod-36094/deepks-abacus:3.7.5v1
        on_demand: 0
train_machine:
  dispatcher: dpdispatcher
  dpdispatcher_machine:
    context_type: lebesguecontext
    batch_type: lebesgue
    local_root: ./
    remote_profile:
      email: *****
      password: *****
      program_id: *****
      input_data:
        log_file: log.train
        err_file: err.train
        job_type: indicate
        grouped: true
        job_name: deepks-train
        disk_size: 100
        scass_type: c32_m128_cpu
        platform: ali
        image_name: registry.dp.tech/dptech/prod-36094/deepks-abacus:3.7.5v1
        on_demand: 0
  dpdispatcher_resources:
    number_node: 1
    cpu_per_node: 8
    group_size: 1
    source_list: [~/.bashrc]
  python: "python" # use python in path
cleanup: false # whether to delete slurm and err files
strict: true # do not allow undefined machine parameters
use_abacus: true # use abacus in scf calculation
```
